### PR TITLE
[ADAM-634] Remove bdg-utils-parquet

### PR DESCRIPTION
**Pull request by tomwhite**
This removes the Parquet code that is no longer used, and moves the general I/O utilities from bdg-utils-parquet to a new module called bdg-utils-io. See https://github.com/bigdatagenomics/adam/issues/634.

Once this is removed and a new release of bdg-utils is made, ADAM should be updated to use the new bdg-utils-io module: https://github.com/bigdatagenomics/adam/compare/master...tomwhite:remove-parquet-utils-part2

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, add to whitelist and test this please.

**Comment by fnothaft** [comment]
Thanks @tomwhite!

**Comment by tomwhite** [comment]
Thanks for merging this @fnothaft. Do you know when the next bdg-utils release will be? Once there's a new release I'll submit https://github.com/bigdatagenomics/adam/compare/master...tomwhite:remove-parquet-utils-part2 as a PR.

**Comment by fnothaft** [comment]
No problem! I'd been hoping to get that cleaned up for a while, so thank you for taking care of that! As for a release, I'll merge in #31 (which is just moving code) and see if I can figure out the remaining issues on #18. Once I've got those taken care of, I can cut a release. Let me spend some time on that either today or tomorrow.

**Comment by tomwhite** [comment]
Sounds good.

**Pull request merged**
