### PR TITLE
Added more granular instrumentation to bdg-utils.

### PR DESCRIPTION
**Pull request by fnothaft**
Migrates @nfergu's metrics work from https://github.com/bigdatagenomics/adam/pull/514 to BDG utils.

### CODE REVIEW

**Comment by shivaram** [comment]
@fnothaft @nfergu This is great stuff ! Just as another Spark App writer, is there any quick start documentation on how to use this ?

**Comment by fnothaft** [comment]
@shivaram ah! Good Q! I don't think there is right now, but we can add that!

**Comment by massie** [comment]
Thanks, @nfergu, for writing the code and @fnothaft for shepherding it into `bdg-utils`. Outstanding contribution.

**Comment by nfergu** [comment]
@shivaram - good point re. the documentation. Now that this is in bdg-utils I will add some to the readme. In the mean time you can find some basic docs in the MetricsContext class.

**Comment by nfergu** [comment]
@shivaram - I've added some documentation here: https://github.com/bigdatagenomics/bdg-utils (see the Instrumentation section)

**Pull request merged**
